### PR TITLE
Update Core.lua to reflect changes to ElitismHelper skill list and spiteful melee support

### PR DESCRIPTION
**Pull request by st-htmn**
update spells for Shadowlands using current spell list from ElitismHelper

### CODE REVIEW

**Comment by edusperoni** [comment]
Thanks! I'm planning on updating it this week or the next (along with the new melee swing detector)

**Comment by st-htmn** [comment]
Didn't read your comment until now, sounds good, I built a temporary solution for myself and added it to the pull request.

**Comment by edusperoni** [comment]
@st-htmn amazing work! I'll merge it and tag a new release.

Do you think it'd make more sense to split it in another view? Or maybe also add it to the fail count? Or instead replacing the spell name with the mob name for melee hits (so we'd have multiple melee icons with different mob names).

I'll release as is for the moment, but it's something to consider in a future release

**Comment by st-htmn** [comment]
Thanks for the appreciation, first time for me playing around with LUA, so I did not understand everything happening.

I think I would leave it in the same view - but adding it to the fail count seems like a good idea. For the moment my version only checks for melee hits from the Spiteful Shades, so mob name wouldn't really matter - that could be a nice addition if more enemies would be tracked.

**Comment by edusperoni** [comment]
@st-htmn I've pushed as an alpha and beta. Can you please try it out once it releases? I'll push it to release if it's all good

Edit: alpha build is out! https://www.curseforge.com/wow/addons/details-elitism-plugin/files/3152624

**Comment by st-htmn** [comment]
image

Did a small melee test run with a second mob-id added - that seems to work. If I find a key, I'll test it there again just to be sure.

**Comment by st-htmn** [comment]
image
image

basically works but I have a small numbers glitch - don't think its from the changes though ... might also be my Details Settings

**Comment by st-htmn** [comment]
image

new abilities look good

**Pull request merged**
