### PR TITLE
Further Changes to S4 Dungeons

### PR DESCRIPTION
**Pull request by Tribunate**
Updates, additions and corrections to @ntowle 's pull request #28

### CODE REVIEW

**Comment by OlivierCodol** [comment]
To have the plugin appear on the AddOns list, I needed to rename the directory from "Details_Elitism-s4" to "Details_Elitism".
Upon doing that, on login and `/console reloadui` I get two LUA errors:

Couldn't open Interface\AddOns\Details_Elitism\Libs\AceEvent-3.0\AceEvent-3.0.xml
Couldn't open Interface\AddOns\Details_Elitism\Libs\AceHook-3.0\AceHook-3.0.xml

Count is 4 for both messages.

It seems the related files exist in the original repo but not on the forked repo? I can't tell if this is intentional.

**Comment by Tribunate** [comment]
Hey there,

I simply forked the repo. As far as I can tell, both libraries are also
missing in the master.
I have added both files into my fork now.

Hope that helps.

  _____

To have the plugin appear on the AddOns list, I needed to rename the
directory from "Details_Elitism-s4" to "Details_Elitism".
Upon doing that, on login and /console reloadui I get two LUA errors:

Couldn't open
Interface\AddOns\Details_Elitism\Libs\AceEvent-3.0\AceEvent-3.0.xml
Couldn't open
Interface\AddOns\Details_Elitism\Libs\AceHook-3.0\AceHook-3.0.xml

Count is 4 for both messages.

It seems the related files exist in the original repo but not on the forked
repo? I can't tell if this is intentional.

**Comment by OlivierCodol** [comment]
This is not my repo but @ntowle 's.
But yes, you are correct. I realized that after posting, which why I removed the comment.

For what it's worth, I tested your fork on Junkyard and it worked without any error popping up.

**Comment by edusperoni** [comment]
Hey! Can you please rebase it onto the latest master? Also, please don't add the libs as these are added by the automated build process. You can see it generates 2 files, one without libs and one with libs: https://github.com/edusperoni/Details_Elitism/releases/tag/v2.6.1

**Pull request merged**
